name: PyPi Release

on:
  push:
    tags:
      - "*"

jobs:
  pypi-publish:
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    environment: release

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build package
        run: |
          python -m build --sdist

      - name: Check metadata
        run: twine check dist/*

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

